server:
  port: 9001

spring:
  application:
    name: module-common
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: yeonbin
    password: 0807
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # 자동으로 테이블 생성 (drop -> create)
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
    accessTokenExpirationTime: 1800000 # 30분 = 1000 * 60 * 30L;
    refreshTokenExpirationTime: 120960000 # ?
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #Eureka Server 명시
  instance:
    leaseRenewalIntervalInSeconds: 30 # 30 seconds
    leaseExpirationDurationInSeconds: 90 # 90 seconds

management:
  endpoints:
    web:
      exposure:
        include: "*"
