server:
  port: 9000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  jwt:
    secret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
  main:
    web-application-type: reactive
  application:
    name: apigateway-server
  cloud:
    gateway:
      default-filters:
        - name: AuthenticationFilter
      routes:
        - id: module-common
          uri: lb://MODULE-COMMON
          predicates:
            - Path=/module-common/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/module-common/(?<segment>.*), /$\{segment}

#        - id: module-common
#          uri: lb://MODULE-COMMON
#          predicates:
#            - Path=/module-common/auth/**
#            - Method=POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/module-common/(?<segment>.*), /$\{segment}
#
#        - id: module-common
#          uri: lb://MODULE-COMMON
#          predicates:
#            - Path=/module-common/user/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/module-common/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter


