server:
  port: 8761

spring:
  application:
    name: module-eureka

eureka:
  client:
    register-with-eureka: false #eureka server를 registry에 등록할지 여부
    fetch-registry: false # 다른 서비스들의 정보를 eureka server로 부터 받아서 로컬메모리에 캐싱할지 여부
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL지정 Eureka API 요청용 URL

  server:
    enable-self-preservation: true # 실제 서비스에서는 가급적 true를 사용하는게 좋다
#    eviction-interval-timer-in-ms: 60 * 1000
#    renewal-percent-threshold: 0.85

management:
  endpoints:
    web:
      exposure:
        include: "*" # Spring Actuator의 어떤 API를 사용할 지 지정하는 설정, * : 우선 모든 API사용
