server:
  port: 9004

spring:
  application:
    name: module-notification

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #Eureka Server 명시
#    instance:
#      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}